// Actividades económicas SII Chile (listado simplificado — puedes reemplazar con el oficial)
export const ACTIVIDADES_ECONOMICAS = [
  { value: '11101', label: 'Cultivo de trigo' },
  { value: '11102', label: 'Cultivo de maíz' },
  { value: '11201', label: 'Cultivo de hortalizas y legumbres' },
  { value: '11301', label: 'Cultivo de frutas' },
  { value: '13001', label: 'Pesca' },
  { value: '20001', label: 'Extracción de carbón' },
  { value: '51001', label: 'Construcción de edificios' },
  { value: '61101', label: 'Comercio al por mayor' },
  { value: '62101', label: 'Comercio al por menor en almacenes no especializados' },
  { value: '62301', label: 'Venta al por menor de alimentos' },
  { value: '71001', label: 'Hoteles y restaurantes' },
  { value: '72101', label: 'Transporte terrestre de pasajeros' },
  { value: '72201', label: 'Transporte de carga por carretera' },
  { value: '74101', label: 'Telecomunicaciones' },
  { value: '81101', label: 'Intermediación financiera' },
  { value: '81201', label: 'Seguros y fondos de pensiones' },
  { value: '83111', label: 'Actividades inmobiliarias' },
  { value: '84101', label: 'Servicios informáticos' },
  { value: '84201', label: 'Procesamiento de datos' },
  { value: '85101', label: 'Investigación y desarrollo' },
  { value: '86101', label: 'Asesoría jurídica' },
  { value: '86201', label: 'Servicios contables' },
  { value: '86301', label: 'Publicidad' },
  { value: '87101', label: 'Arriendo de maquinarias' },
  { value: '91111', label: 'Administración pública' },
  { value: '92111', label: 'Enseñanza básica' },
  { value: '92201', label: 'Enseñanza universitaria' },
  { value: '93111', label: 'Actividades hospitalarias' },
  { value: '93121', label: 'Consultorios médicos' },
  { value: '95001', label: 'Servicios de limpieza' },
  { value: '95201', label: 'Peluquerías y salones de belleza' },
  { value: '96001', label: 'Otras actividades de servicios' },
]

export const BANCOS = [
  { value: 'banco_chile', label: 'Banco de Chile' },
  { value: 'banco_estado', label: 'BancoEstado' },
  { value: 'santander', label: 'Banco Santander' },
  { value: 'bci', label: 'BCI' },
  { value: 'itau', label: 'Itaú' },
  { value: 'scotiabank', label: 'Scotiabank' },
  { value: 'security', label: 'Banco Security' },
  { value: 'falabella', label: 'Banco Falabella' },
  { value: 'ripley', label: 'Banco Ripley' },
  { value: 'consorcio', label: 'Banco Consorcio' },
  { value: 'coopeuch', label: 'Coopeuch' },
  { value: 'tenpo', label: 'Tenpo' },
  { value: 'mercadopago', label: 'Mercado Pago' },
]

export const REGIONES = [
  'Región de Arica y Parinacota',
  'Región de Tarapacá',
  'Región de Antofagasta',
  'Región de Atacama',
  'Región de Coquimbo',
  'Región de Valparaíso',
  'Región Metropolitana de Santiago',
  'Región del Libertador General Bernardo O\'Higgins',
  'Región del Maule',
  'Región de Ñuble',
  'Región del Biobío',
  'Región de La Araucanía',
  'Región de Los Ríos',
  'Región de Los Lagos',
  'Región de Aysén del General Carlos Ibáñez del Campo',
  'Región de Magallanes y de la Antártica Chilena',
]
